modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "valkyrienmissiles"
version = "${version}"
displayName = "Valkyrien Missiles"
authors = "StoneTrench, FixIsDaddy"
description = '''
Add missiles to Valkyrien Skies.
'''
#logoFile = ""

[[dependencies.valkyrienmissiles]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.valkyrienmissiles]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.valkyrienmissiles]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"