modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/StoneTrench/ValkyrienMissiles/issues"
license = "MIT"

[[mods]]
modId = "valkyrienmissiles"
version = "${version}"
displayName = "Valkyrien Missiles"
authors = ["StoneTrench", "FixIsDaddy"]
description = '''
Add missiles to Valkyrien Skies.
'''
logoFile = "icon.png"

[[dependencies.valkyrienmissiles]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.valkyrienmissiles]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.valkyrienmissiles]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.valkyrienmissiles]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"